# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'Flickz' do
    # Pods for Flickz
    pod 'AFNetworking'
    pod 'MBProgressHUD'

end
